import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const html = readFileSync(new URL('../index.html', import.meta.url), 'utf8');
const illustrated = readFileSync(new URL('../illustrated.html', import.meta.url), 'utf8');
const reboot = readFileSync(new URL('../reboot.html', import.meta.url), 'utf8');
const legacy = readFileSync(new URL('../legacy.html', import.meta.url), 'utf8');
const main = readFileSync(new URL('../src/main.js', import.meta.url), 'utf8');
const rebootEntry = readFileSync(new URL('../src/reboot/entry.js', import.meta.url), 'utf8');

assert.match(html, /하루와 사라진 이름/);
assert.match(html, /src="\/src\/storybook3d\/entry\.js"/);
assert.match(html, /<canvas[^>]+data-storybook-canvas/);
assert.match(html, /data-webgl-fallback/);
assert.doesNotMatch(html, /data-action-canvas|SIGNAL|TRACE|location\.replace/);
assert.match(illustrated, /src\/illustrated\/entry\.js/);
assert.match(illustrated, /<canvas[^>]+data-action-canvas/);
assert.match(illustrated, /data-game-hud/);
assert.match(illustrated, /data-control="left"/);
assert.match(illustrated, /data-control="right"/);
assert.match(illustrated, /data-control="jump"/);
assert.match(illustrated, /data-control="attack"/);
assert.match(illustrated, /data-control="trace"/);
assert.match(illustrated, /aria-live="polite"/);
assert.match(reboot, /<script type="module" src="\/src\/reboot\/entry\.js"><\/script>/);
assert.match(legacy, /<script type="module" src="\/src\/main\.js"><\/script>/);
assert.match(main, /THREE/);
assert.match(main, /initEthicsQuest3D/);
assert.match(rebootEntry, /resolveCampaignSceneId/);
console.log('DOM smoke passed: 3D storybook is canonical and 2D plus both 3D rollback routes remain wired');
