export function queryCampaignDom(game) {
  const one = (selector) => game.querySelector(selector);
  return {
    game,
    canvas: one('[data-action-canvas]'),
    titleScreen: one('[data-title-screen]'),
    newGameButton: one('[data-new-game]'),
    continueButton: one('[data-continue-game]'),
    storyPanel: one('[data-story-panel]'),
    storySpeaker: one('[data-story-speaker]'),
    storyLine: one('[data-story-line]'),
    storyNext: one('[data-story-next]'),
    choicePanel: one('[data-choice-panel]'),
    choicePrompt: one('[data-choice-prompt]'),
    choiceOptions: one('[data-choice-options]'),
    resultPanel: one('[data-result-panel]'),
    resultKicker: one('[data-result-kicker]'),
    resultTitle: one('[data-result-title]'),
    resultLine: one('[data-result-line]'),
    resultCost: one('[data-result-cost]'),
    nextChapterButton: one('[data-next-chapter]'),
    endingPanel: one('[data-ending-panel]'),
    endingTitle: one('[data-ending-title]'),
    endingLine: one('[data-ending-line]'),
    endingCost: one('[data-ending-cost]'),
    reportList: one('[data-report-list]'),
    prompt: one('[data-objective-prompt]'),
    mission: one('[data-mission]'),
    zone: one('[data-zone]'),
    chapterNumber: one('[data-chapter-number]'),
    chapterTime: one('[data-chapter-time]'),
    chapterTopic: one('[data-chapter-topic]'),
    chapterButtons: [...game.querySelectorAll('[data-chapter-button]')],
    health: one('[data-health]'),
    liveStatus: one('[data-live-status]'),
    controls: [...game.querySelectorAll('[data-control]')],
    helpButton: one('[data-game-help]'),
    helpDialog: one('[data-help-dialog]'),
    helpClose: one('[data-help-close]'),
    restartButton: one('[data-restart]'),
    printButton: one('[data-print-report]'),
    primitiveShowcase: one('[data-primitive-showcase]'),
    ethicsRule: one('[data-ethics-rule]'),
    ethicsState: one('[data-ethics-state]'),
    ethicsLesson: one('[data-ethics-lesson]'),
    ethicsCost: one('[data-ethics-cost]')
  };
}
